{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "autojson",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autojson-0.0.9.jar",
          "url": "autojson-0.0.9.jar",
          "size": 74854,
          "sha512": "7a2acba6f1c61d17c853cfb27c87af1bf1a5eceb79863a1675d8c3f30ca0dd9222f1db0a304d19d8cbe07c736e11be3b2f18764174421c9a5226e64d84f0cfeb",
          "sha256": "e56e750efe5eda06c4f92755a5ee175e3f08bb634ea8fb0295f2bb51fa9354bb",
          "sha1": "a15512eec7b5832387141a94f1c0e97930c1911f",
          "md5": "a48742aea2ffc5015e9fc63cd0d3f421"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "autojson-0.0.9.jar",
          "url": "autojson-0.0.9.jar",
          "size": 74854,
          "sha512": "7a2acba6f1c61d17c853cfb27c87af1bf1a5eceb79863a1675d8c3f30ca0dd9222f1db0a304d19d8cbe07c736e11be3b2f18764174421c9a5226e64d84f0cfeb",
          "sha256": "e56e750efe5eda06c4f92755a5ee175e3f08bb634ea8fb0295f2bb51fa9354bb",
          "sha1": "a15512eec7b5832387141a94f1c0e97930c1911f",
          "md5": "a48742aea2ffc5015e9fc63cd0d3f421"
        }
      ]
    }
  ]
}
