{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "hytale-gradle",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hytale-gradle-0.0.0.jar",
          "url": "hytale-gradle-0.0.0.jar",
          "size": 13711,
          "sha512": "9f135c76c5e94e499f876271d9d40fc18fcafa54472d33df65a2099e34b78309a1ca53495e285cb973a1ff85c88f947606bc751d6061b6db4ec87eabde9f159e",
          "sha256": "cd174e1a3632c8e97d9ead54414bfa12e00af65877d07d94d7ef2201114ff3ff",
          "sha1": "3b95a2d13aa9e7c16111b8e9b975c0494042f075",
          "md5": "94a879f5801054e2c30a3ee890b791a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "hytale-gradle-0.0.0.jar",
          "url": "hytale-gradle-0.0.0.jar",
          "size": 13711,
          "sha512": "9f135c76c5e94e499f876271d9d40fc18fcafa54472d33df65a2099e34b78309a1ca53495e285cb973a1ff85c88f947606bc751d6061b6db4ec87eabde9f159e",
          "sha256": "cd174e1a3632c8e97d9ead54414bfa12e00af65877d07d94d7ef2201114ff3ff",
          "sha1": "3b95a2d13aa9e7c16111b8e9b975c0494042f075",
          "md5": "94a879f5801054e2c30a3ee890b791a1"
        }
      ]
    }
  ]
}
