{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "hytale-gradle",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hytale-gradle-0.0.0.jar",
          "url": "hytale-gradle-0.0.0.jar",
          "size": 13760,
          "sha512": "5f012a6feb1c98ea8a7ae98d0446330b31734b1e3858934fee53e6310abe2f0481782089c92b7ef377277ebf8726a39c161bc5c89a90d64d6d12b201842808c9",
          "sha256": "311f7c958150689306ea49492f2755abfe64bb8e721c1eba569cca8b56959885",
          "sha1": "137fec78dafed49cbf7523381322b1cfc23ebaa4",
          "md5": "00b431410a10759c9abf46cd04dfbd58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "hytale-gradle-0.0.0.jar",
          "url": "hytale-gradle-0.0.0.jar",
          "size": 13760,
          "sha512": "5f012a6feb1c98ea8a7ae98d0446330b31734b1e3858934fee53e6310abe2f0481782089c92b7ef377277ebf8726a39c161bc5c89a90d64d6d12b201842808c9",
          "sha256": "311f7c958150689306ea49492f2755abfe64bb8e721c1eba569cca8b56959885",
          "sha1": "137fec78dafed49cbf7523381322b1cfc23ebaa4",
          "md5": "00b431410a10759c9abf46cd04dfbd58"
        }
      ]
    }
  ]
}
