{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "hytale-gradle",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hytale-gradle-0.0.0.jar",
          "url": "hytale-gradle-0.0.0.jar",
          "size": 13764,
          "sha512": "ecf22d6ef073684807af810bf4f67daec090c322ede27c4a6f3b30659f82a1949165d781149e2ffc17779d666480599f0fcaf9d00abb6eafb1ee50afc79e0f51",
          "sha256": "276bc86657098e13bbd87274cdaad9cb09b608faf655f1eec71ac7b712d980c8",
          "sha1": "1295f99999d37b8d5b38093dece4803dc521ff84",
          "md5": "4ce781f5eabf2fe51e1d9618a9f56443"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "hytale-gradle-0.0.0.jar",
          "url": "hytale-gradle-0.0.0.jar",
          "size": 13764,
          "sha512": "ecf22d6ef073684807af810bf4f67daec090c322ede27c4a6f3b30659f82a1949165d781149e2ffc17779d666480599f0fcaf9d00abb6eafb1ee50afc79e0f51",
          "sha256": "276bc86657098e13bbd87274cdaad9cb09b608faf655f1eec71ac7b712d980c8",
          "sha1": "1295f99999d37b8d5b38093dece4803dc521ff84",
          "md5": "4ce781f5eabf2fe51e1d9618a9f56443"
        }
      ]
    }
  ]
}
