{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "autojson",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autojson-0.0.5.jar",
          "url": "autojson-0.0.5.jar",
          "size": 74725,
          "sha512": "17a679051cae6631ba7dd795a5887f5438a1f6e12a97496ae27f650367631fe324d49c53e991c0b7a7efe2f9da5b36eb59b3611cc60feb08d3977d0b49eb1848",
          "sha256": "194c22c08276430edfbdddd0cbcdbd15824fa49a45bbf3eb8e0df122e46b6a8f",
          "sha1": "d17afc81cfcc2bac74818852f0e7b89ff4d8a6e8",
          "md5": "3e550fe113f94a29545d65f318ba9e50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "autojson-0.0.5.jar",
          "url": "autojson-0.0.5.jar",
          "size": 74725,
          "sha512": "17a679051cae6631ba7dd795a5887f5438a1f6e12a97496ae27f650367631fe324d49c53e991c0b7a7efe2f9da5b36eb59b3611cc60feb08d3977d0b49eb1848",
          "sha256": "194c22c08276430edfbdddd0cbcdbd15824fa49a45bbf3eb8e0df122e46b6a8f",
          "sha1": "d17afc81cfcc2bac74818852f0e7b89ff4d8a6e8",
          "md5": "3e550fe113f94a29545d65f318ba9e50"
        }
      ]
    }
  ]
}
