{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "autojson",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autojson-0.0.3.jar",
          "url": "autojson-0.0.3.jar",
          "size": 73748,
          "sha512": "c9db1f7e8a9285c2b6fd5585b0908e866b591457117e81fc330e68e51354062a623ca417ab774f72285e5e8f0ca8e7152b7fc33cdd137c1b30c3e0e599b5fa5e",
          "sha256": "763d5c6dcab8cebef2b09fac7faeabb18acf11df95f5ae09653030586e45263a",
          "sha1": "818689ee5e721971b3672d6f89805e10a294defc",
          "md5": "726f90efd3862d2bffee7da3c675cdbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "autojson-0.0.3.jar",
          "url": "autojson-0.0.3.jar",
          "size": 73748,
          "sha512": "c9db1f7e8a9285c2b6fd5585b0908e866b591457117e81fc330e68e51354062a623ca417ab774f72285e5e8f0ca8e7152b7fc33cdd137c1b30c3e0e599b5fa5e",
          "sha256": "763d5c6dcab8cebef2b09fac7faeabb18acf11df95f5ae09653030586e45263a",
          "sha1": "818689ee5e721971b3672d6f89805e10a294defc",
          "md5": "726f90efd3862d2bffee7da3c675cdbe"
        }
      ]
    }
  ]
}
