{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "autojson",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autojson-1.0.0.jar",
          "url": "autojson-1.0.0.jar",
          "size": 66715,
          "sha512": "2a215c435b7d5459344da6338a6d081a522fe64a40fe9a465b6c3d235af5617919e955ec9dbb000d5554289850fff92d54ca2f64792262fe70ac3fd68abd6bd7",
          "sha256": "614ce41c7bdf664d5425fea4f51e3030a9dd06f46254d3a88117dd2e1d0e1b32",
          "sha1": "410a121841b933a21aa72f0d973269562789c31c",
          "md5": "a9188b3c20f75f6dda6040d0b8f90208"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "autojson-1.0.0.jar",
          "url": "autojson-1.0.0.jar",
          "size": 66715,
          "sha512": "2a215c435b7d5459344da6338a6d081a522fe64a40fe9a465b6c3d235af5617919e955ec9dbb000d5554289850fff92d54ca2f64792262fe70ac3fd68abd6bd7",
          "sha256": "614ce41c7bdf664d5425fea4f51e3030a9dd06f46254d3a88117dd2e1d0e1b32",
          "sha1": "410a121841b933a21aa72f0d973269562789c31c",
          "md5": "a9188b3c20f75f6dda6040d0b8f90208"
        }
      ]
    }
  ]
}
