{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "autojson",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autojson-0.0.8.jar",
          "url": "autojson-0.0.8.jar",
          "size": 74838,
          "sha512": "75db651f1fd616b5538fdb15bc3a7ed9c10a8c1c0a7902f5fdc1b51c69c030683176e36c7acddccd22616e3972c811d6a4c34247f2e82a4c24c58e1e3c938bcb",
          "sha256": "f418d00931c320a7d0439e95eb99c0f81c45307cb0166919b6a5f35e590d5820",
          "sha1": "5fa1699257d93134f73708fc1c863851f1640724",
          "md5": "828c124d51b5cae888e9ec92498e25d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "autojson-0.0.8.jar",
          "url": "autojson-0.0.8.jar",
          "size": 74838,
          "sha512": "75db651f1fd616b5538fdb15bc3a7ed9c10a8c1c0a7902f5fdc1b51c69c030683176e36c7acddccd22616e3972c811d6a4c34247f2e82a4c24c58e1e3c938bcb",
          "sha256": "f418d00931c320a7d0439e95eb99c0f81c45307cb0166919b6a5f35e590d5820",
          "sha1": "5fa1699257d93134f73708fc1c863851f1640724",
          "md5": "828c124d51b5cae888e9ec92498e25d7"
        }
      ]
    }
  ]
}
