{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "hytale-gradle",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hytale-gradle-0.0.6.jar",
          "url": "hytale-gradle-0.0.6.jar",
          "size": 12248,
          "sha512": "09c84fc351aec968a2fcf5ca1aab8c06ed7d305d7fbc1e4198046b9a188f4044c48b7a27bfbde9115c9fe9e941fb0d667858ffaf9605930766c225ffeabba4c9",
          "sha256": "e3fee6e3b151675cdb6eea52ffd18d009ddb054dfe46aabbc4a023be9e26117d",
          "sha1": "87c746d80694c9f4aabde40d1a3ca38a8781a70d",
          "md5": "d74b94b105094c1556cce6f9db22de2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "hytale-gradle-0.0.6.jar",
          "url": "hytale-gradle-0.0.6.jar",
          "size": 12248,
          "sha512": "09c84fc351aec968a2fcf5ca1aab8c06ed7d305d7fbc1e4198046b9a188f4044c48b7a27bfbde9115c9fe9e941fb0d667858ffaf9605930766c225ffeabba4c9",
          "sha256": "e3fee6e3b151675cdb6eea52ffd18d009ddb054dfe46aabbc4a023be9e26117d",
          "sha1": "87c746d80694c9f4aabde40d1a3ca38a8781a70d",
          "md5": "d74b94b105094c1556cce6f9db22de2e"
        }
      ]
    }
  ]
}
