{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "hytale-gradle",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hytale-gradle-0.0.5.jar",
          "url": "hytale-gradle-0.0.5.jar",
          "size": 12161,
          "sha512": "ebbe867fc5b1907d7383fd5952561ed7e1bb8c6cabc8fe32eb067d6a8d565163c555bd398061cfb152d3ee57b7061f6f1b93c8a8a5f154a2e151f70e3b8eea4e",
          "sha256": "c112cd308049b7ec3ccd62eeaccc4541970bf7e1613d7db6ee73954627468d1f",
          "sha1": "9447aac9ea1498dc906941db13afcb5311a7bcdf",
          "md5": "5717e3af1a9fa5ce0eb9f94ee274a10b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "hytale-gradle-0.0.5.jar",
          "url": "hytale-gradle-0.0.5.jar",
          "size": 12161,
          "sha512": "ebbe867fc5b1907d7383fd5952561ed7e1bb8c6cabc8fe32eb067d6a8d565163c555bd398061cfb152d3ee57b7061f6f1b93c8a8a5f154a2e151f70e3b8eea4e",
          "sha256": "c112cd308049b7ec3ccd62eeaccc4541970bf7e1613d7db6ee73954627468d1f",
          "sha1": "9447aac9ea1498dc906941db13afcb5311a7bcdf",
          "md5": "5717e3af1a9fa5ce0eb9f94ee274a10b"
        }
      ]
    }
  ]
}
