{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.drtheo",
    "module": "autojson",
    "version": "0.1.0-dev.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autojson-0.1.0-dev.1.jar",
          "url": "autojson-0.1.0-dev.1.jar",
          "size": 76508,
          "sha512": "660936ec7104654bd1ce79055b31f365a7cf5890053033072093025be921d5d1ca7a9160e8b10c96cdaa03ba32708524e1fade86c9ae657537efcf2fc63ff993",
          "sha256": "97c12587863d22e0d29305f8e95a3d7fdca3b4fe1d8a500d4fa2d9e17b1fbe2a",
          "sha1": "f9573554abb69bc845515a1277aaf64273bf0936",
          "md5": "bfa87954c183568687aed712a050887e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autojson-0.1.0-dev.1.jar",
          "url": "autojson-0.1.0-dev.1.jar",
          "size": 76508,
          "sha512": "660936ec7104654bd1ce79055b31f365a7cf5890053033072093025be921d5d1ca7a9160e8b10c96cdaa03ba32708524e1fade86c9ae657537efcf2fc63ff993",
          "sha256": "97c12587863d22e0d29305f8e95a3d7fdca3b4fe1d8a500d4fa2d9e17b1fbe2a",
          "sha1": "f9573554abb69bc845515a1277aaf64273bf0936",
          "md5": "bfa87954c183568687aed712a050887e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autojson-0.1.0-dev.1-sources.jar",
          "url": "autojson-0.1.0-dev.1-sources.jar",
          "size": 37020,
          "sha512": "630180ec25ce7eefa45bcfb213df4e58f375a1e48ee378d59a41802d0d0a51ba1155446379e96e74fd079d06f6d446df65b13a1a5ec1db7f6f58d256642893a7",
          "sha256": "591dd2a3ff87c3962ec3149fffe9774237e9770c82d51fc98fd2c0166f0e6f8a",
          "sha1": "dd20d1d3d867c3f5ebabb9b2583bb927ac06e3f8",
          "md5": "835cc3526993102b72bfe9f305fea6bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autojson-0.1.0-dev.1-javadoc.jar",
          "url": "autojson-0.1.0-dev.1-javadoc.jar",
          "size": 316165,
          "sha512": "cd06b4d0fc5e3c5e655d9128b996c072edf740033914f7d2e8339cb47333fbf5a2a2f65229a77f962c3e8477e96adb01d55462ac5f9d05a49b4d8acd7b781f06",
          "sha256": "10fe4d9e0ac76a784d9d42f3a54c1714f6bd60b09462dd1b4e4f8f9ebbf70e2c",
          "sha1": "a9ba009d80445e8d4760f7b979b31f8937c97523",
          "md5": "c762970b279b0b6d499bad2d1e8fad7d"
        }
      ]
    }
  ]
}
